---
- hosts: vagrant
  become: yes
  tasks:
    - name: install tree on remote server
      yum: 
        name: tree
        state: present
#        register: tree_store
      when: "'vagrant' in inventory_hostname" 
     
    - debug:
        msg: "display value is {{inventory_hostname}}"
        
    - name: create directory
      file:
        dest: /home/vagrant/chenna
        state: directory
        mode: 0755
     
    - name: checkout the git repo
      git:
        repo: https://github.com/Gchennareddy/testrepo.git
        dest: /home/vagrant
        
      
