---
- hosts: vagrant
  become: yes
  tasks:
    - name: install tree on remote server
      yum: 
        name: tree
        state: present
#        register: tree_store
      when: 'vagrant' in inventory_hostname 
     
    - debug:
        msg: "display value is {{inventory_hostname}}"
      
